export const FORMS_CONFIG = [
  // ── Form 1: Akuan Penerimaan Wang Tunai ─────────────────────────────────────
  {
    id: "akuan-wang-tunai",
    title: "Akuan Penerimaan Wang Tunai",
    subtitle: "Borang akuan penerimaan wang tunai untuk program",
    autoFillAkuanWangTunai: true,
    hideSuratKelulusan: true,
    allowSubmitToChoice: true,
    // Filled by the reviewer (whoever this was submitted to) at approval time —
    // distinct from Section C's "Pengesahan" above, which the treasurer fills
    // at submission time acknowledging receipt of the cash.
    reviewerSection: {
      label: "Pengesahan (Diserahkan Oleh)",
      kind: "fixed",
      fields: [
        { key: "tandatangan_diserah", label: "Tandatangan",  type: "signature", required: true },
        { key: "nama_penuh_diserah",  label: "Nama Penuh",   type: "text",      required: true, autoFillReviewer: "fullName" },
        { key: "tarikh_diserah",      label: "Tarikh",       type: "date",      required: true, autoFillReviewer: "today" },
        { key: "no_tel_diserah",      label: "No. Telefon",  type: "text",      required: true, autoFillReviewer: "phone" },
      ],
    },
    sections: [
      {
        id: "A",
        label: "Butiran Penerima",
        required: true,
        fields: [
          { key: "namapenuh_penerima", label: "Nama Penuh",           type: "text",     required: true,  placeholder: "AHMAD BIN HASSAN" },
          { key: "no_kp_penerima",     label: "No. Kad Pengenalan",   type: "text",     required: true,  placeholder: "980101-01-1234" },
          { key: "organisasi",         label: "Organisasi",           type: "text",     required: true,  placeholder: "Kelab Komputer UTM" },
          { key: "alamat",             label: "Alamat",               type: "textarea", required: true },
        ],
      },
      {
        id: "B",
        label: "Butiran Penerimaan Wang",
        required: true,
        fields: [
          { key: "jumlah",        label: "Jumlah (RM)",   type: "number", required: true,  placeholder: "500.00" },
          { key: "tujuan",        label: "Tujuan",        type: "text",   required: true,  placeholder: "Kutipan yuran penyertaan program" },
          { key: "program",       label: "Program",       type: "text",   required: true,  placeholder: "Hari Teknologi 2025" },
          { key: "anjuran",       label: "Anjuran",       type: "text",   required: true,  placeholder: "Kelab Komputer UTM" },
          { key: "tarikh_terima", label: "Tarikh Terima", type: "date",   required: true },
        ],
      },
      {
        id: "C",
        label: "Pengesahan",
        required: true,
        fields: [
          { key: "tandatangan_pengesahan", label: "Tandatangan",           type: "signature", required: true },
          { key: "diterima_nama",          label: "Nama Penuh",            type: "text",      required: true,  placeholder: "Nama pegawai penerima" },
          { key: "diterima_tarikh",        label: "Tarikh",                type: "date",      required: true },
          { key: "diterima_tel",           label: "No. Telefon",           type: "text",      required: true,  placeholder: "012-3456789" },
          { key: "ulasan",                 label: "Ulasan / Jika Berkaitan", type: "textarea", required: false, placeholder: "Catatan tambahan jika berkaitan" },
        ],
      },
    ],
    fields: [
      { key: "namapenuh_penerima", label: "Nama Penuh Penerima",             type: "text",     required: true,  placeholder: "AHMAD BIN HASSAN" },
      { key: "no_kp_penerima",     label: "No. Kad Pengenalan Penerima",     type: "text",     required: true,  placeholder: "980101-01-1234" },
      { key: "organisasi",         label: "Organisasi",                      type: "text",     required: true,  placeholder: "Kelab Komputer UTM" },
      { key: "alamat",             label: "Alamat",                          type: "textarea", required: true },
      { key: "jumlah",             label: "Jumlah (RM)",                     type: "number",   required: true,  placeholder: "500.00" },
      { key: "tujuan",             label: "Tujuan",                          type: "text",     required: true,  placeholder: "Kutipan yuran penyertaan program" },
      { key: "program",            label: "Program",                         type: "text",     required: true,  placeholder: "Hari Teknologi 2025" },
      { key: "anjuran",            label: "Anjuran",                         type: "text",     required: true,  placeholder: "Kelab Komputer UTM" },
      { key: "tarikh_terima",      label: "Tarikh Terima",                   type: "date",     required: true },
      { key: "diterima_nama",      label: "Pengesahan — Nama Penuh",         type: "text",     required: true,  placeholder: "Nama pegawai penerima" },
      { key: "diterima_tarikh",    label: "Pengesahan — Tarikh",             type: "date",     required: true },
      { key: "diterima_tel",       label: "Pengesahan — No. Telefon",        type: "text",     required: true,  placeholder: "012-3456789" },
      { key: "ulasan",             label: "Ulasan / Jika Berkaitan",         type: "textarea", required: false, placeholder: "Catatan tambahan jika berkaitan" },
    ],
    rowColumns: null,
  },

  // ── Form 2: Baucer Bayaran ───────────────────────────────────────────────────
  {
    id: "baucer-bayaran",
    title: "Baucer Bayaran",
    subtitle: "Borang baucer bayaran program",
    autoFillFields: {
      nama_penerima:   "fullName",
      disediakan_nama: "fullName",
      disediakan_tarikh: "today",
    },
    // Filled by the reviewer at approval time — a separate sign-off chain from
    // the treasurer's own "Baucer Disediakan Oleh" fields above (Section B).
    // The reviewer picks whichever of these roles applies to them and signs it.
    reviewerSection: {
      label: "Pengesahan",
      kind: "choice",
      minSelected: 1,
      options: [
        { key: "baucer_disediakan",  label: "Baucer Disediakan Oleh",   fields: [{ key: "sig_baucer_disediakan",  label: "Tandatangan", type: "signature", required: true }] },
        { key: "bayaran_diluluskan", label: "Bayaran Diluluskan Oleh",  fields: [{ key: "sig_bayaran_diluluskan", label: "Tandatangan", type: "signature", required: true }] },
        { key: "cek_ditandatangani", label: "Cek Ditandatangani Oleh",  fields: [{ key: "sig_cek_ditandatangani", label: "Tandatangan", type: "signature", required: true }] },
      ],
    },
    sections: [
      {
        id: "A",
        label: "Maklumat Baucer",
        required: true,
        fields: [
          { key: "tarikh",               label: "Tarikh",                       type: "date",     required: true },
          { key: "nama_akaun",           label: "Nama Akaun",                   type: "text",     required: true,  placeholder: "KELAB KOMPUTER UTM" },
          { key: "no_baucer",            label: "No. Baucer",                   type: "text",     required: true,  placeholder: "BB-2025-001" },
          { key: "baki_tabung",          label: "Baki Tabung (RM)",             type: "number",   required: false, placeholder: "2000.00" },
          { key: "jumlah_pengeluaran",   label: "Jumlah Pengeluaran (RM)",      type: "number",   required: true,  placeholder: "350.00" },
          { key: "baki_tabung_terakhir", label: "Baki Tabung Terakhir (RM)",    type: "number",   required: false, placeholder: "1650.00" },
          { key: "catatan",              label: "Catatan",                      type: "text",     required: false, placeholder: "Bayaran percetakan brosur" },
        ],
      },
      {
        id: "B",
        label: "Butiran Penerima",
        required: true,
        fields: [
          { key: "nama_penerima",         label: "Nama Penerima",  type: "text",      required: true,  placeholder: "Kedai Reka Digital" },
          { key: "alamat",                label: "Alamat Penerima", type: "textarea", required: true },
          { key: "tujuan",                label: "Tujuan",         type: "text",      required: true,  placeholder: "Bayaran percetakan brosur untuk program" },
          { key: "catitan",               label: "Catitan",        type: "text",      required: false, placeholder: "Dibayar tunai" },
          { key: "cek_no",                label: "Cek No.",        type: "text",      required: false, placeholder: "123456" },
          { key: "tandatangan_penyediaan",label: "Tandatangan",    type: "signature", required: true },
          { key: "disediakan_nama",       label: "Nama",           type: "text",      required: true,  placeholder: "AHMAD BIN HASSAN" },
          { key: "disediakan_tarikh",     label: "Tarikh",         type: "date",      required: true },
        ],
      },
    ],
    fields: [
      { key: "tarikh",               label: "Tarikh",                       type: "date",     required: true },
      { key: "nama_akaun",           label: "Nama Akaun",                   type: "text",     required: true,  placeholder: "KELAB KOMPUTER UTM" },
      { key: "no_baucer",            label: "No. Baucer",                   type: "text",     required: true,  placeholder: "BB-2025-001" },
      { key: "baki_tabung",          label: "Baki Tabung (RM)",             type: "number",   required: false, placeholder: "2000.00" },
      { key: "jumlah_pengeluaran",   label: "Jumlah Pengeluaran (RM)",      type: "number",   required: true,  placeholder: "350.00" },
      { key: "baki_tabung_terakhir", label: "Baki Tabung Terakhir (RM)",    type: "number",   required: false, placeholder: "1650.00" },
      { key: "catatan",              label: "Catatan",                      type: "text",     required: false, placeholder: "Bayaran percetakan brosur" },
      { key: "nama_penerima",        label: "Nama Penerima",                type: "text",     required: true,  placeholder: "Kedai Reka Digital" },
      { key: "alamat",               label: "Alamat Penerima",              type: "textarea", required: true },
      { key: "tujuan",               label: "Tujuan",                       type: "text",     required: true,  placeholder: "Bayaran percetakan brosur untuk program" },
      { key: "catitan",              label: "Catitan",                      type: "text",     required: false, placeholder: "Dibayar tunai" },
      { key: "cek_no",               label: "Cek No.",                      type: "text",     required: false, placeholder: "123456" },
      { key: "disediakan_nama",      label: "Disediakan Oleh — Nama",       type: "text",     required: true,  placeholder: "AHMAD BIN HASSAN" },
      { key: "disediakan_tarikh",    label: "Disediakan Oleh — Tarikh",     type: "date",     required: true },
    ],
    rowColumns: null,
  },

  // ── Form 3: Tuntutan Bayaran Balik Mendahulukan Wang ────────────────────────
  {
    id: "tuntutan-bayaran-balik",
    title: "Tuntutan Bayaran Balik Mendahulukan Wang",
    subtitle: "Borang tuntutan bayaran balik pendahuluan wang",
    autoFillFields: {
      nama_penuh: "fullName",
      no_matrik:  "matricNumber",
      no_tel:     "phone",
      tarikh:     "today",
    },
    enforceRequiredFields: true,
    mandatoryAttachments: [
      { key: "senaraiResitBayaran",       label: "Senarai Resit Bayaran",         hint: "Muat naik senarai resit bayaran. (PDF sahaja)",                      required: true,  maxFiles: 1, accept: "application/pdf" },
      { key: "resitAsal",                 label: "Resit Asal",                    hint: "Muat naik salinan resit asal. (PDF sahaja, boleh lebih daripada satu)", required: true,  maxFiles: 5, accept: "application/pdf" },
      { key: "salinanSuratKelulusan",     label: "Salinan Surat Kelulusan",       hint: "Muat naik salinan surat kelulusan program. (PDF sahaja)",           required: true,  maxFiles: 1, accept: "application/pdf" },
      { key: "borangTukarTarikh",         label: "Borang Tukar Tarikh",           hint: "Muat naik borang tukar tarikh jika berkaitan. (PDF sahaja)",        required: false, maxFiles: 1, accept: "application/pdf" },
      { key: "tentatifPenyataKewangan",   label: "Tentatif & Penyata Kewangan",   hint: "Muat naik tentatif dan penyata kewangan program. (PDF sahaja)",     required: true,  maxFiles: 2, accept: "application/pdf" },
    ],
    sections: [
      {
        id: "A",
        label: "Maklumat Pemohon",
        required: true,
        fields: [
          { key: "nama_pemohon",    label: "Nama Pemohon (Kelab / Persatuan)",                    type: "text",     required: true, placeholder: "Kelab Komputer UTM" },
          { key: "tujuan_pembelian",label: "Tujuan Pembelian (Nama Program, Tarikh & Tempat)",   type: "textarea", required: true, placeholder: "Pembelian hadiah pemenang, Program Inovasi 2025, 15 Mac 2025, Dewan Canselor UTM" },
          { key: "jumlah_tuntutan", label: "Jumlah Tuntutan (RM)",                               type: "number",   required: true, placeholder: "450.00" },
        ],
      },
      {
        id: "B",
        label: "Perakuan Bayaran",
        required: true,
        fields: [
          { key: "perakuan_terma", label: "Perakuan", type: "info", required: false, content: [
            "Saya mengaku bahawa tuntutan ini adalah benar dan telah membuat bayaran menggunakan wang sendiri.",
            "Sekiranya tuntutan yang dikemukakan adalah tidak benar dan berlaku penyalahgunaan, saya boleh disiasat dan dikenakan tindakan di bawah Kaedah-kaedah Universiti Teknologi Malaysia (Tatatertib Pelajar-Pelajar) 1999 atau Akta Badan-badan Berkanun (Tertib dan Surcaj) Akta 605.",
            "Barang/Perkhidmatan telah diterima dengan sempurna mengikut spesifikasi yang ditetapkan.",
            "Tuntutan ini telah disemak dan belum dibayar.",
            "Semua Peraturan Universiti telah dipatuhi.",
          ] },
          { key: "perakuan_akui", label: "Saya telah membaca dan bersetuju dengan Perakuan Bayaran di atas.", type: "checkbox", required: true },
          { key: "tandatangan_pemohon", label: "Tandatangan", type: "signature", required: true },
          { key: "nama_penuh", label: "Nama Penuh",  type: "text", required: true, placeholder: "AHMAD BIN HASSAN" },
          { key: "no_matrik",  label: "No. Matrik",  type: "text", required: true, placeholder: "A21EC0001" },
          { key: "no_tel",     label: "No. Tel",     type: "text", required: true, placeholder: "012-3456789" },
          { key: "tarikh",     label: "Tarikh",      type: "date", required: true },
        ],
      },
    ],
    fields: [
      { key: "nama_pemohon",    label: "Nama Pemohon",                                          type: "text",     required: true, placeholder: "Kelab Komputer UTM" },
      { key: "tujuan_pembelian",label: "Tujuan Pembelian (Nama Program, Tarikh & Tempat)",      type: "textarea", required: true, placeholder: "Pembelian hadiah pemenang, Program Inovasi 2025, 15 Mac 2025, Dewan Canselor UTM" },
      { key: "jumlah_tuntutan", label: "Jumlah Tuntutan (RM)",                                  type: "number",   required: true, placeholder: "450.00" },
      { key: "perakuan_akui",   label: "Perakuan Bayaran — Pengakuan",                          type: "checkbox", required: true },
      { key: "nama_penuh",      label: "Nama Penuh",                                            type: "text",     required: true, placeholder: "AHMAD BIN HASSAN" },
      { key: "no_matrik",       label: "No. Matrik",                                            type: "text",     required: true, placeholder: "A21EC0001" },
      { key: "no_tel",          label: "No. Tel",                                               type: "text",     required: true, placeholder: "012-3456789" },
      { key: "tarikh",          label: "Tarikh",                                                type: "date",     required: true },
    ],
    rowColumns: null,
  },

  // ── Form 4: Senarai Invois, Bil dan Tuntutan untuk Dibayar ──────────────────
  {
    id: "senarai-invois",
    title: "Senarai Invois, Bil dan Tuntutan untuk Dibayar",
    subtitle: "Senarai invois, bil dan tuntutan pembayaran",
    sections: [
      {
        id: "A",
        label: "Maklumat Borang",
        required: true,
        fields: [
          { key: "no_siri",        label: "No. Siri",                  type: "text", required: true, placeholder: "INV-2025-001" },
          { key: "persatuan_kelab",label: "Persatuan / Kelab / JKM",   type: "text", required: true, placeholder: "Kelab Komputer UTM" },
          { key: "tarikh",         label: "Tarikh",                    type: "date", required: true },
        ],
      },
      {
        id: "B",
        label: "Tandatangan",
        required: true,
        fields: [
          { key: "nama_jawatan", label: "Nama & Jawatan", type: "text", required: true, placeholder: "Ahmad Hassan, Bendahari" },
        ],
      },
    ],
    fields: [
      { key: "no_siri",        label: "No. Siri",                  type: "text", required: true, placeholder: "INV-2025-001" },
      { key: "persatuan_kelab",label: "Persatuan / Kelab / JKM",   type: "text", required: true, placeholder: "Kelab Komputer UTM" },
      { key: "tarikh",         label: "Tarikh",                    type: "date", required: true },
      { key: "nama_jawatan",   label: "Nama & Jawatan (Tandatangan)", type: "text", required: true, placeholder: "Ahmad Hassan, Bendahari" },
    ],
    rowColumns: [
      { key: "nama_penerima",  label: "Nama Penerima / Alamat",    placeholder: "Pembekal Alat Tulis Sdn Bhd" },
      { key: "no_kp",          label: "No. K/P",                   placeholder: "980101-01-1234" },
      { key: "jenis_tuntutan", label: "Jenis Tuntutan",            placeholder: "A (Bil)" },
      { key: "no_vot",         label: "No. Vot",                   placeholder: "2024-01" },
      { key: "no_bil_invois",  label: "No. Bil / Invois",          placeholder: "INV-001" },
      { key: "jumlah_dibayar", label: "Jumlah Dibayar (RM)",       placeholder: "250.00" },
    ],
  },

  // ── Form 5: Tuntutan Bayaran Program ────────────────────────────────────────
  {
    id: "tuntutan-elaun-penceramah",
    title: "Tuntutan Bayaran Program",
    subtitle: "Elaun Penceramah/Hadiah Pemenang/DLL",
    autoFillFields: {
      nama_penerima: "fullName",
    },
    rowColumnsAllRequired: true,
    rowsRequireAtLeastOne: true,
    enforceRequiredFields: true,
    mandatoryAttachments: [
      { key: "suratKelulusanProgram", label: "Surat Kelulusan Program",   hint: "Muat naik salinan surat kelulusan program. (PDF sahaja)",              required: true,  maxFiles: 1, accept: "application/pdf" },
      { key: "borangTukarTarikh",     label: "Borang Tukar Tarikh",       hint: "Muat naik borang tukar tarikh jika berkaitan. (PDF sahaja)",           required: false, maxFiles: 1, accept: "application/pdf" },
      { key: "salinanIc",             label: "Salinan IC",                hint: "Muat naik salinan kad pengenalan. (PDF sahaja)",                       required: true,  maxFiles: 1, accept: "application/pdf" },
      { key: "salinanPenyataAkaun",   label: "Salinan Penyata Akaun",     hint: "Muat naik salinan penyata akaun bank. (PDF sahaja)",                   required: true,  maxFiles: 1, accept: "application/pdf" },
      { key: "dokumenSokongan",       label: "Dokumen Sokongan",          hint: "Muat naik dokumen sokongan tambahan jika ada. (maksimum 2 fail, PDF sahaja)", required: false, maxFiles: 2, accept: "application/pdf" },
    ],
    sections: [
      {
        id: "A",
        label: "Maklumat Penerima",
        required: true,
        fields: [
          { key: "nama_penerima",   label: "Nama Penerima",        type: "text",   required: true, placeholder: "Prof. Dr. Ahmad Hassan" },
          { key: "jenis_elaun",     label: "Jenis Elaun",          type: "text",   required: true, placeholder: "Elaun Penceramah" },
          { key: "nama_program",    label: "Nama Program",         type: "text",   required: true, placeholder: "Seminar AI 2025" },
          { key: "tarikh_tuntutan", label: "Tarikh",               type: "date",   required: true },
          { key: "jumlah_tuntutan", label: "Jumlah Tuntutan (RM)", type: "number", required: true, placeholder: "300.00" },
        ],
      },
      {
        id: "B",
        label: "Perakuan Bayaran",
        required: true,
        fields: [
          { key: "perakuan_terma", label: "Perakuan", type: "info", required: false, content: [
            "Saya mengaku bahawa tuntutan ini adalah benar dan telah membuat bayaran menggunakan wang sendiri.",
            "Sekiranya tuntutan yang dikemukakan adalah tidak benar dan berlaku penyalahgunaan, saya boleh disiasat dan dikenakan tindakan di bawah Kaedah-kaedah Universiti Teknologi Malaysia (Tatatertib Pelajar-Pelajar) 1999 atau Akta Badan-badan Berkanun (Tertib dan Surcaj) Akta 605.",
            "Barang/Perkhidmatan telah diterima dengan sempurna mengikut spesifikasi yang ditetapkan.",
            "Tuntutan ini telah disemak dan belum dibayar.",
            "Semua Peraturan Universiti telah dipatuhi.",
          ] },
          { key: "perakuan_akui", label: "Saya telah membaca dan bersetuju dengan Perakuan Bayaran di atas.", type: "checkbox", required: true },
          { key: "tandatangan_penyediaan", label: "Tandatangan", type: "signature", required: true },
          { key: "disediakan_tarikh",      label: "Tarikh",      type: "date",      required: true },
        ],
      },
      {
        id: "Lampiran A",
        label: "Senarai Penerima",
        required: true,
        isRowSection: true,
      },
    ],
    fields: [
      { key: "nama_penerima",     label: "Nama Penerima",              type: "text",   required: true, placeholder: "Prof. Dr. Ahmad Hassan" },
      { key: "jenis_elaun",       label: "Jenis Elaun",                type: "text",   required: true, placeholder: "Elaun Penceramah" },
      { key: "nama_program",      label: "Nama Program",               type: "text",   required: true, placeholder: "Seminar AI 2025" },
      { key: "tarikh_tuntutan",   label: "Tarikh",                     type: "date",   required: true },
      { key: "jumlah_tuntutan",   label: "Jumlah Tuntutan (RM)",       type: "number", required: true, placeholder: "300.00" },
      { key: "perakuan_akui",     label: "Perakuan Bayaran — Pengakuan", type: "checkbox", required: true },
      { key: "disediakan_tarikh",label: "Disediakan Oleh — Tarikh",   type: "date",   required: true },
    ],
    rowColumns: [
      { key: "nama_penerima",  label: "Nama Penerima",     placeholder: "Prof. Dr. Ahmad Hassan", inputType: "text" },
      { key: "no_ic",          label: "No. IC",            placeholder: "980101-01-1234",         inputType: "text" },
      { key: "nama_bank",      label: "Nama Bank",         placeholder: "Maybank",                 inputType: "text" },
      { key: "no_akaun",       label: "No. Akaun",         placeholder: "1234567890",              inputType: "text" },
      { key: "jenis_tuntutan", label: "Jenis Tuntutan",    placeholder: "Elaun Penceramah",        inputType: "text" },
      { key: "jumlah",         label: "Jumlah (RM)",       placeholder: "300.00",                  inputType: "money" },
    ],
  },

  // ── Form 6: Pendahuluan Aktiviti ────────────────────────────────────────────
  {
    id: "pendahuluan-aktiviti",
    title: "Pendahuluan Aktiviti",
    subtitle: "Borang Pendahuluan Aktiviti Pelajar",
    autoFillFields: {
      persatuan_kelab: "club",
      tarikh:          "today",
      nama_penerima:   "fullName",
      no_kp:           "icNumber",
      aktiviti:        "program",
      nama:            "fullName",
    },
    enforceRequiredFields: true,
    jawatanCombineWithProgram: true,
    hideSuratKelulusan: true,
    mandatoryAttachments: [
      { key: "suratPermohonanPendahuluan", label: "Surat Permohonan Pendahuluan",                              hint: "Muat naik surat permohonan pendahuluan. (PDF sahaja)", required: true,  maxFiles: 1, accept: "application/pdf" },
      { key: "lampiranPerincianKewangan",  label: "Lampiran Perincian Kewangan Jumlah Pendahuluan yang Dimohon", hint: "Muat naik perincian kewangan jumlah pendahuluan yang dimohon. (PDF sahaja)", required: true,  maxFiles: 1, accept: "application/pdf" },
      { key: "suratKelulusanUtmacad",      label: "Surat Kelulusan / UTMACAD",                                  hint: "Muat naik surat kelulusan atau UTMACAD. (PDF sahaja)", required: true,  maxFiles: 1, accept: "application/pdf" },
      { key: "borangPenangguhan",          label: "Borang Permohonan Penangguhan / Perubahan Maklumat",         hint: "Muat naik borang penangguhan / perubahan maklumat jika berkaitan. (PDF sahaja)", required: false, maxFiles: 1, accept: "application/pdf" },
    ],
    sections: [
      {
        id: "A",
        label: "Maklumat Pendahuluan",
        required: true,
        fields: [
          { key: "no_siri",            label: "No. Siri",                 type: "text",     required: true, placeholder: "PA-2025-001" },
          { key: "persatuan_kelab",    label: "Persatuan / Kelab / JKM",  type: "text",     required: true, placeholder: "Kelab Komputer UTM" },
          { key: "tarikh",             label: "Tarikh",                   type: "date",     required: true },
          { key: "nama_penerima",      label: "Nama Penerima",            type: "text",     required: true, placeholder: "AHMAD BIN HASSAN" },
          { key: "alamat",             label: "Alamat Penerima",          type: "textarea", required: true },
          { key: "no_kp",              label: "No. Kad Pengenalan",       type: "text",     required: true, placeholder: "980101-01-1234" },
          { key: "program",            label: "Program",                  type: "text",     required: true, placeholder: "Program Komuniti Siswa 2025" },
          { key: "aktiviti",           label: "Aktiviti",                 type: "text",     required: true, placeholder: "Majlis Anugerah Kepimpinan" },
          { key: "jumlah_pendahuluan", label: "Jumlah Pendahuluan (RM)",  type: "number",   required: true, placeholder: "200.00" },
        ],
      },
      {
        id: "B",
        label: "Tandatangan",
        required: true,
        fields: [
          { key: "tandatangan_pendahuluan", label: "Tandatangan", type: "signature", required: true },
          { key: "nama",                    label: "Nama",        type: "text",      required: true, placeholder: "AHMAD BIN HASSAN" },
          { key: "jawatan",                 label: "Jawatan",     type: "select",    required: true, options: ["Pengerusi", "Naib Pengerusi", "Setiausaha", "Bendahari"] },
        ],
      },
    ],
    fields: [
      { key: "no_siri",             label: "No. Siri",                  type: "text",     required: true,  placeholder: "PA-2025-001" },
      { key: "persatuan_kelab",     label: "Persatuan / Kelab / JKM",   type: "text",     required: true,  placeholder: "Kelab Komputer UTM" },
      { key: "tarikh",              label: "Tarikh",                    type: "date",     required: true },
      { key: "nama_penerima",       label: "Nama Penerima",             type: "text",     required: true,  placeholder: "AHMAD BIN HASSAN" },
      { key: "alamat",              label: "Alamat Penerima",           type: "textarea", required: true },
      { key: "no_kp",               label: "No. Kad Pengenalan",        type: "text",     required: true,  placeholder: "980101-01-1234" },
      { key: "program",             label: "Program",                   type: "text",     required: true,  placeholder: "Program Komuniti Siswa 2025" },
      { key: "aktiviti",            label: "Aktiviti",                  type: "text",     required: true,  placeholder: "Majlis Anugerah Kepimpinan" },
      { key: "jumlah_pendahuluan",  label: "Jumlah Pendahuluan (RM)",   type: "number",   required: true,  placeholder: "200.00" },
      { key: "nama",                label: "Nama (Tandatangan)",        type: "text",     required: true,  placeholder: "AHMAD BIN HASSAN" },
      { key: "jawatan",             label: "Jawatan (Tandatangan)",     type: "select",   required: true,  options: ["Pengerusi", "Naib Pengerusi", "Setiausaha", "Bendahari"] },
    ],
    rowColumns: null,
  },

  // ── Form 7: Borang Permohonan Pengecualian Cukai ────────────────────────────
  {
    id: "permohonan-pengecualian-cukai",
    title: "Borang Permohonan Pengecualian Cukai",
    subtitle: "Borang Permohonan Pengecualian Cukai Subseksyen 44(6)",
    autoFillPemohon: true,
    enforceRequiredFields: true,
    jawatanCombineWithProgram: true,
    rowColumnsAllRequired: true,
    fixedRowCount: 5,
    requireAllRowsFilled: true,
    hideSuratKelulusan: true,
    mandatoryAttachments: [
      { key: "suratKelulusanProgram",  label: "Surat Kelulusan Program",                     hint: "Muat naik surat kelulusan program. (PDF atau imej diterima)" },
      { key: "suratPenajaanPihakLuar", label: "Surat Penajaan Pihak Luar / Dalam Kampus UTM", hint: "Muat naik surat penajaan pihak luar atau dalam kampus UTM. (PDF atau imej diterima)" },
    ],
    sections: [
      {
        id: "A",
        label: "Maklumat Pemohon",
        required: true,
        fields: [
          { key: "nama",       label: "Nama",        type: "text",   required: true, placeholder: "AHMAD BIN HASSAN" },
          { key: "no_matrik",  label: "No. Matrik",  type: "text",   required: true, placeholder: "A21EC0001" },
          { key: "no_kp",      label: "No. KP",      type: "text",   required: true, placeholder: "980101-01-1234" },
          { key: "no_telefon", label: "No. Telefon", type: "text",   required: true, placeholder: "012-3456789" },
          { key: "jawatan",    label: "Jawatan",     type: "select", required: true, options: ["Pengarah", "Timb. Pengarah", "Setiausaha", "Bendahari", "Crew/Committee"] },
        ],
      },
      {
        id: "B",
        label: "Maklumat Program",
        required: true,
        fields: [
          { key: "nama_program",          label: "Nama Program",            type: "text", required: true,  placeholder: "Program Komuniti Siswa 2025" },
          { key: "persatuan_jkm",         label: "Persatuan / JKM",         type: "text", required: true,  placeholder: "Kelab Komputer UTM" },
          { key: "tarikh_program_dari",   label: "Tarikh Program — Dari",   type: "date", required: true },
          { key: "tarikh_program_hingga", label: "Tarikh Program — Hingga", type: "date", required: true },
          { key: "tarikh_kutipan_dari",   label: "Tarikh Kutipan — Dari",   type: "date", required: false },
          { key: "tarikh_kutipan_hingga", label: "Tarikh Kutipan — Hingga", type: "date", required: false },
        ],
      },
      {
        id: "C",
        label: "Senarai Penaja Berpotensi (5 Penaja)",
        required: true,
        isRowSection: true,
      },
      {
        id: "D",
        label: "Tandatangan Pemohon",
        required: true,
        fields: [
          { key: "tandatangan_pemohon", label: "Tandatangan",       type: "signature", required: true },
          { key: "tarikh_tandatangan",  label: "Tarikh Tandatangan", type: "date",     required: true },
        ],
      },
    ],
    fields: [
      { key: "nama",                  label: "Nama",                            type: "text",   required: true,  placeholder: "AHMAD BIN HASSAN" },
      { key: "no_matrik",             label: "No. Matrik",                      type: "text",   required: true,  placeholder: "A21EC0001" },
      { key: "no_kp",                 label: "No. KP",                          type: "text",   required: true,  placeholder: "980101-01-1234" },
      { key: "no_telefon",            label: "No. Telefon",                     type: "text",   required: true,  placeholder: "012-3456789" },
      { key: "jawatan",               label: "Jawatan",                         type: "select", required: true,  options: ["Pengarah", "Timb. Pengarah", "Setiausaha", "Bendahari", "Crew/Committee"] },
      { key: "nama_program",          label: "Nama Program",                    type: "text",   required: true,  placeholder: "Program Komuniti Siswa 2025" },
      { key: "persatuan_jkm",         label: "Persatuan / JKM",                type: "text",   required: true,  placeholder: "Kelab Komputer UTM" },
      { key: "tarikh_program_dari",   label: "Tarikh Program — Dari",          type: "date",   required: true },
      { key: "tarikh_program_hingga", label: "Tarikh Program — Hingga",        type: "date",   required: true },
      { key: "tarikh_kutipan_dari",   label: "Tarikh Kutipan — Dari",          type: "date",   required: false },
      { key: "tarikh_kutipan_hingga", label: "Tarikh Kutipan — Hingga",        type: "date",   required: false },
      { key: "tarikh_tandatangan",    label: "Tarikh Tandatangan Pemohon",     type: "date",   required: true },
    ],
    rowColumns: [
      { key: "nama_penaja",       label: "Nama Syarikat / Penaja Berpotensi", placeholder: "Syarikat ABC Sdn Bhd", inputType: "text" },
      { key: "alamat_penaja",     label: "Alamat Penaja",                     placeholder: "No. 12, Jalan Teknologi, 81300 Skudai, Johor", inputType: "address" },
      { key: "no_telefon_penaja", label: "No. Telefon",                       placeholder: "012-3456789", inputType: "text" },
    ],
  },

  // ── Form 8: Penyata Kewangan + Senarai Resit ────────────────────────────────
  {
    id: "penyata-kewangan-resit",
    title: "Penyata Kewangan + Senarai Resit",
    subtitle: "Penyata kewangan program dan senarai resit",
    rowColumnsAllRequired: true,
    rowsAutoFromTransactions: true,
    hideSuratKelulusan: true,
    allowSubmitToChoice: true,
    submitToOptions: ["bendahari_kelab", "advisor", "pegawai"],
    autoFillFields: {
      persatuan_kelab:     "club",
      aktiviti_program:    "program",
      nama_bendahari:      "fullName",
      no_telefon_bendahari:"phone",
      tarikh_penyediaan:   "today",
    },
    sections: [
      {
        id: "A",
        label: "Maklumat Program",
        required: true,
        fields: [
          { key: "no_ruj_persatuan", label: "No. Ruj. Persatuan",      type: "text", required: true, placeholder: "KC-UTM-2025-001" },
          { key: "persatuan_kelab",  label: "Persatuan / Kelab / JKM", type: "text", required: true, placeholder: "Kelab Komputer UTM" },
          { key: "aktiviti_program", label: "Aktiviti / Program",      type: "text", required: true, placeholder: "Majlis Anugerah Kepimpinan 2025" },
          { key: "tarikh_program",   label: "Tarikh Program",          type: "date", required: true },
          { key: "tempat_program",   label: "Tempat Program",          type: "text", required: true, placeholder: "Dewan Canselor UTM" },
        ],
      },
      {
        id: "B",
        label: "Wang Masuk",
        required: false,
        fields: [
          { key: "peruntukan_hepa_pendahuluan", label: "Peruntukan HEPA — Pendahuluan (RM)", type: "number", required: false, placeholder: "1000.00" },
          { key: "peruntukan_hepa_baki",        label: "Peruntukan HEPA — Baki (RM)",        type: "number", required: false, placeholder: "500.00" },
          { key: "tabung_persatuan",            label: "Tabung Persatuan (RM)",              type: "number", required: false, placeholder: "200.00" },
          { key: "yuran_penyertaan",            label: "Yuran Penyertaan (RM)",              type: "number", required: false, placeholder: "150.00" },
          { key: "penajaan",                    label: "Penajaan (RM)",                      type: "number", required: false, placeholder: "0.00" },
          { key: "sumbangan_lain",              label: "Sumbangan Lain (RM)",                type: "number", required: false, placeholder: "0.00" },
        ],
      },
      {
        id: "C",
        label: "Wang Keluar",
        required: false,
        fields: [
          { key: "makan_minum",  label: "Makan / Minum (RM)",  type: "number", required: false, placeholder: "300.00" },
          { key: "peralatan",    label: "Peralatan (RM)",       type: "number", required: false, placeholder: "200.00" },
          { key: "pengangkutan", label: "Pengangkutan (RM)",    type: "number", required: false, placeholder: "100.00" },
          { key: "perhubungan",  label: "Perhubungan (RM)",     type: "number", required: false, placeholder: "50.00" },
          { key: "cenderamata",  label: "Cenderamata (RM)",     type: "number", required: false, placeholder: "0.00" },
          { key: "alat_tulis",   label: "Alat Tulis (RM)",      type: "number", required: false, placeholder: "50.00" },
        ],
      },
      {
        id: "D",
        label: "Senarai Resit Bayaran",
        required: true,
        isRowSection: true,
        rowSectionFields: [
          { key: "nama_program", label: "Nama Program", type: "text", required: true, placeholder: "Majlis Anugerah Kepimpinan 2025" },
          { key: "anjuran",      label: "Anjuran",      type: "text", required: true, placeholder: "Kelab Komputer UTM" },
        ],
      },
      {
        id: "E",
        label: "Disediakan Oleh",
        required: true,
        fields: [
          { key: "tandatangan_penyediaan", label: "Tandatangan",           type: "signature", required: true },
          { key: "nama_bendahari",         label: "Nama Bendahari Program", type: "text", required: true, placeholder: "AHMAD BIN HASSAN" },
          { key: "no_telefon_bendahari",   label: "No. Telefon Bendahari",  type: "text", required: true, placeholder: "012-3456789" },
          { key: "tarikh_penyediaan",      label: "Tarikh Penyediaan",      type: "date", required: true },
        ],
      },
    ],
    fields: [
      { key: "no_ruj_persatuan",            label: "No. Ruj. Persatuan",                      type: "text",   required: true,  placeholder: "KC-UTM-2025-001" },
      { key: "persatuan_kelab",             label: "Persatuan / Kelab / JKM",                 type: "text",   required: true,  placeholder: "Kelab Komputer UTM" },
      { key: "aktiviti_program",            label: "Aktiviti / Program",                      type: "text",   required: true,  placeholder: "Majlis Anugerah Kepimpinan 2025" },
      { key: "tarikh_program",              label: "Tarikh Program",                          type: "date",   required: true },
      { key: "tempat_program",              label: "Tempat Program",                          type: "text",   required: true,  placeholder: "Dewan Canselor UTM" },
      { key: "peruntukan_hepa_pendahuluan", label: "Peruntukan HEPA — Pendahuluan (RM)",     type: "number", required: false, placeholder: "1000.00" },
      { key: "peruntukan_hepa_baki",        label: "Peruntukan HEPA — Baki (RM)",            type: "number", required: false, placeholder: "500.00" },
      { key: "tabung_persatuan",            label: "Tabung Persatuan (RM)",                   type: "number", required: false, placeholder: "200.00" },
      { key: "yuran_penyertaan",            label: "Yuran Penyertaan (RM)",                   type: "number", required: false, placeholder: "150.00" },
      { key: "penajaan",                    label: "Penajaan (RM)",                           type: "number", required: false, placeholder: "0.00" },
      { key: "sumbangan_lain",              label: "Sumbangan Lain (RM)",                     type: "number", required: false, placeholder: "0.00" },
      { key: "makan_minum",                 label: "Makan / Minum (RM)",                     type: "number", required: false, placeholder: "300.00" },
      { key: "peralatan",                   label: "Peralatan (RM)",                         type: "number", required: false, placeholder: "200.00" },
      { key: "pengangkutan",                label: "Pengangkutan (RM)",                      type: "number", required: false, placeholder: "100.00" },
      { key: "perhubungan",                 label: "Perhubungan (RM)",                       type: "number", required: false, placeholder: "50.00" },
      { key: "cenderamata",                 label: "Cenderamata (RM)",                       type: "number", required: false, placeholder: "0.00" },
      { key: "alat_tulis",                  label: "Alat Tulis (RM)",                        type: "number", required: false, placeholder: "50.00" },
      { key: "nama_program",                label: "Nama Program",                            type: "text",   required: true,  placeholder: "Majlis Anugerah Kepimpinan 2025" },
      { key: "anjuran",                     label: "Anjuran",                                 type: "text",   required: true,  placeholder: "Kelab Komputer UTM" },
      { key: "nama_bendahari",              label: "Nama Bendahari Program",                 type: "text",   required: true,  placeholder: "AHMAD BIN HASSAN" },
      { key: "no_telefon_bendahari",        label: "No. Telefon Bendahari",                  type: "text",   required: true,  placeholder: "012-3456789" },
      { key: "tarikh_penyediaan",           label: "Tarikh Penyediaan",                      type: "date",   required: true },
    ],
    rowColumns: [
      { key: "tarikh_resit",     label: "Tarikh Resit",     placeholder: "2025-04-15" },
      { key: "perkara",          label: "Perkara",          placeholder: "Bayaran makan minum peserta" },
      { key: "no_resit",         label: "No. Resit",        placeholder: "RCP-001" },
      { key: "jumlah",           label: "Jumlah (RM)",      placeholder: "150.00" },
      { key: "tujuan_pembelian", label: "Tujuan Pembelian", placeholder: "Makan minum peserta program" },
    ],
  },

  // ── Form 9: Borang Penyerahan Cek / Wang Tunai ──────────────────────────────
  {
    id: "penyerahan-cek-wang-tunai",
    title: "Borang Penyerahan Cek / Wang Tunai",
    subtitle: "Bagi Tujuan Permohonan Pengecualian Cukai Subseksyen 44(6)",
    rowsUsePopout: true,
    rowColumnsAllRequired: true,
    rowsRequireAtLeastOne: true,
    enforceRequiredFields: true,
    hideSuratKelulusan: true,
    autoFillDisediakanOleh: true,
    mandatoryAttachments: [
      { key: "suratKelulusanCukai", label: "Salinan Surat Kelulusan Pengecualian Cukai", hint: "Muat naik salinan surat kelulusan pengecualian cukai. (PDF atau imej diterima)" },
      { key: "buktiPembayaran",     label: "Salinan No. Cek / Bank / Tunai / EFT",        hint: "Muat naik salinan resit / bukti cek, bank, tunai atau EFT. (PDF atau imej diterima)" },
    ],
    advisorSection: {
      label: "Disahkan Oleh",
      fields: [
        { key: "disahkan_nama",    label: "Nama",    type: "text", required: false, placeholder: "Nama pegawai pengesah" },
        { key: "disahkan_jawatan", label: "Jawatan", type: "text", required: false, placeholder: "Jawatan pegawai pengesah" },
        { key: "disahkan_tarikh",  label: "Tarikh",  type: "date", required: false },
      ],
    },
    sections: [
      {
        id: "A",
        label: "Maklumat Program",
        required: true,
        fields: [
          { key: "nama_persatuan", label: "Nama JKM / Persatuan / Kelab",                   type: "text", required: true,  placeholder: "Kelab Komputer UTM" },
          { key: "nama_program",   label: "Nama Program",                                   type: "text", required: true,  placeholder: "Program Komuniti Siswa 2025" },
          { key: "no_rujukan",     label: "No. Rujukan Surat Kelulusan Pengecualian Cukai", type: "text", required: true,  placeholder: "KEW/AP/2025/001" },
        ],
      },
      {
        id: "B",
        label: "Senarai Penyumbang",
        required: true,
        isRowSection: true,
      },
      {
        id: "C",
        label: "Disediakan Oleh",
        required: true,
        fields: [
          { key: "disediakan_tandatangan", label: "Tandatangan", type: "signature", required: true },
          { key: "disediakan_nama",        label: "Nama",        type: "text",      required: true, placeholder: "AHMAD BIN HASSAN" },
          { key: "disediakan_jawatan",     label: "Jawatan",     type: "text",      required: true, placeholder: "Pengerusi / Bendahari" },
          { key: "disediakan_tarikh",      label: "Tarikh",      type: "date",      required: true },
        ],
      },
    ],
    fields: [
      { key: "nama_persatuan",    label: "Nama JKM / Persatuan / Kelab",                    type: "text", required: true,  placeholder: "Kelab Komputer UTM" },
      { key: "nama_program",      label: "Nama Program",                                    type: "text", required: true,  placeholder: "Program Komuniti Siswa 2025" },
      { key: "no_rujukan",        label: "No. Rujukan Surat Kelulusan Pengecualian Cukai",  type: "text", required: true,  placeholder: "KEW/AP/2025/001" },
      { key: "disediakan_nama",   label: "Disediakan Oleh — Nama",                          type: "text", required: true,  placeholder: "AHMAD BIN HASSAN" },
      { key: "disediakan_jawatan",label: "Disediakan Oleh — Jawatan",                       type: "text", required: true,  placeholder: "Pengerusi / Bendahari" },
      { key: "disediakan_tarikh", label: "Disediakan Oleh — Tarikh",                        type: "date", required: true },
      { key: "disahkan_nama",     label: "Disahkan Oleh — Nama",                            type: "text", required: false, placeholder: "Nama pegawai pengesah" },
      { key: "disahkan_jawatan",  label: "Disahkan Oleh — Jawatan",                         type: "text", required: false, placeholder: "Jawatan pegawai pengesah" },
      { key: "disahkan_tarikh",   label: "Disahkan Oleh — Tarikh",                          type: "date", required: false },
    ],
    rowColumns: [
      { key: "nama_penyumbang",   label: "Nama Penyumbang",              placeholder: "Syarikat ABC Sdn Bhd",   inputType: "text" },
      { key: "alamat_penuh",      label: "Alamat Penuh Penyumbang",      placeholder: "No. 12, Jalan Teknologi, 81300 Skudai, Johor", inputType: "address" },
      { key: "tarikh_sumbangan",  label: "Tarikh Sumbangan",             placeholder: "2025-04-01",             inputType: "date" },
      { key: "jumlah_sumbangan",  label: "Jumlah Sumbangan (RM)",        placeholder: "1000.00",                inputType: "money" },
      { key: "no_cek_bank",       label: "No. Cek / Bank / Tunai / EFT", placeholder: "CHQ-123456",             inputType: "uppercase" },
    ],
  },
];
